# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Pytorch_Nerf',
                'doc_host': 'https://ssoufiene.github.io',
                'git_url': 'https://github.com/ssoufiene/Pytorch_Nerf',
                'lib_path': 'Pytorch_Nerf'},
  'syms': {'Pytorch_Nerf.core': {'Pytorch_Nerf.core.foo': ('core.html#foo', 'Pytorch_Nerf/core.py')}}}
